//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNewService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyNewDatabaseTables : DbContext
    {
        public MyNewDatabaseTables()
            : base("name=MyNewDatabaseTables")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableLinks> TableLinks { get; set; }
        public virtual DbSet<TableMedia> TableMedia { get; set; }
        public virtual DbSet<TableText> TableText { get; set; }
    }
}
